# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_et_rue', models.CharField(max_length=100)),
                ('appart_bati', models.CharField(max_length=42)),
                ('boite_postale', models.CharField(max_length=42)),
                ('code_postal', models.CharField(max_length=10)),
                ('commune', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_fixe', models.CharField(max_length=15)),
                ('tel_port', models.CharField(max_length=15)),
                ('num_fax', models.CharField(max_length=15)),
                ('adr_mail', models.CharField(max_length=52)),
                ('site_int', models.CharField(max_length=100)),
                ('adresse_postale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boite.Adresse_Post')),
            ],
        ),
        migrations.CreateModel(
            name='Direct_Soc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_dir', models.CharField(max_length=50)),
                ('mere_dir', models.CharField(max_length=42)),
                ('resp_dir', models.CharField(max_length=84)),
                ('contact_resp', models.CharField(max_length=100)),
                ('adr_post_dir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boite.Adresse_Post')),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=42)),
                ('telephone', models.CharField(max_length=15)),
                ('fax', models.CharField(max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('description', models.TextField(null=True)),
                ('registre_commerce', models.CharField(max_length=42)),
                ('adresse_mail', models.CharField(max_length=81)),
                ('site_web', models.CharField(max_length=100)),
                ('adresse_postale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boite.Adresse_Post')),
            ],
        ),
        migrations.CreateModel(
            name='Forme_Juri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_juri', models.CharField(max_length=42)),
                ('description_juri', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metier_Activ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_meti', models.CharField(max_length=42)),
                ('description_meti', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Respon_Boite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_resp', models.CharField(max_length=42)),
                ('prenom_resp', models.CharField(max_length=42)),
                ('titre_resp', models.CharField(max_length=42)),
                ('tel_resp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Secteur_Activ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_sect', models.CharField(max_length=42)),
                ('description_sect', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='entreprise',
            name='forme_juridique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boite.Forme_Juri'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='metier_ent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boite.Metier_Activ'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boite.Respon_Boite'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='secteur_activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boite.Secteur_Activ'),
        ),
    ]
