# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boite', '0002_entreprise_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='adresse_postale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boite.Adresse_Post'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de creation'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='fax',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='site_web',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='telephone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
