# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boite', '0003_auto_20160330_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='description_resume',
            field=models.TextField(null=True),
        ),
    ]
