# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boite', '0004_entreprise_description_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adresse_post',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='adresse_post',
            name='commune',
        ),
        migrations.AddField(
            model_name='adresse_post',
            name='code_postal_commune',
            field=models.CharField(default='81000 Albi', max_length=110),
        ),
    ]
