# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boite', '0005_auto_20160402_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse_post',
            name='appart_bati',
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='adresse_post',
            name='boite_postale',
            field=models.CharField(max_length=42, null=True),
        ),
    ]
