# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boite', '0006_auto_20160402_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
