# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boite', '0007_entreprise_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_evt', models.CharField(max_length=100, null=True)),
                ('resume_evt', models.CharField(max_length=200, null=True)),
                ('date_evt', models.DateTimeField(auto_now_add=True, null=True, verbose_name="Date de l'événement")),
                ('detail_evt', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact_gene',
            name='adresse_postale',
        ),
        migrations.RemoveField(
            model_name='direct_soc',
            name='adr_post_dir',
        ),
        migrations.AddField(
            model_name='respon_boite',
            name='mail_resp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Contact_Gene',
        ),
        migrations.DeleteModel(
            name='Direct_Soc',
        ),
        migrations.AddField(
            model_name='entreprise',
            name='evenement_entr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boite.Evenement'),
        ),
    ]
