# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boite', '0009_auto_20160403_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='date_creation',
            field=models.DateTimeField(null=True, verbose_name='Date de creation'),
        ),
    ]
