# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='texte',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titre',
        ),
    ]
