# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='user',
        ),
    ]
