# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=100)),
                ('secteur_activite', models.CharField(max_length=42)),
                ('responsable', models.CharField(max_length=42)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
