# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='secteur_activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Secteur'),
        ),
    ]
