# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160307_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date',
            new_name='date_publication',
        ),
    ]
