# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_menus',
            name='menu_contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_menus.Contact'),
        ),
    ]
