# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_menus', '0002_auto_20160330_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='carte',
        ),
    ]
