# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_menus', '0003_remove_contact_carte'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='My_contact',
        ),
    ]
